language: android
jdk: oraclejdk8
sudo: false

env:
  global:
    - export ANDROID_SDK_ROOT=/usr/local/android-sdk
    - export ANDROID_HOME=~/.android

android:
  components:
    - android-25
    - build-tools-25.0.3
    - sys-img-armeabi-v7a-google_apis-25

before_cache:
  - rm -f  ~/.gradle/caches/modules-2/modules-2.lock
  - rm -fr ~/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.android/build-cache

before_install:
  - export PATH=${ANDROID_SDK_ROOT}/tools/bin:$PATH
  - mkdir -p ~/.AndroidStudio
  - touch ~/.AndroidStudio/options.xml
  - touch ~/.android/emu-update-last-check.ini

before_script:
  - echo no | android create avd --force -n test -t android-25 --abi google_apis/armeabi-v7a
  - emulator -engine classic -avd test -no-audio -no-window -verbose &
  - android-wait-for-emulator
  - adb shell input keyevent 82 &

script: "./gradlew clean build connectedCheck -PdisablePreDex --stacktrace"
